greeting:
  value: Yo from yaml
spring:
  application:
    name: servicetwo
server:
  port: ${port:8090}
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
      preferIpAddress: true  
